import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Box, Button, Grid, Input, Sheet } from "@mui/joy";
import SendIcon from "@mui/icons-material/Send";

export default function Home() {
  return (
    <>
      <Head>
        <title>CatGPT 🐈</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        spacing={2}
        sx={{ flexGrow: 1, width: "100%", height: "100%" }}
      >
        <Grid className={styles.sidebar} xs={2}></Grid>
        <Grid xs={10} sx={{ display: "flex", maxHeight: "100vh" }}>
          <Box sx={{ display: "flex", flexDirection: "column", flex: 1 }}>
            <Box sx={{ display: "flex", flex: 1 }}></Box>
            <Box sx={{ display: "flex", justifyContent: "center" }}>
              <Input
                sx={{
                  boxShadow: "sm",
                  flex: 1,
                  maxWidth: "40em",
                }}
                endDecorator={
                  <Button variant="outlined">
                    <SendIcon />
                  </Button>
                }
                placeholder="Chat with the cat..."
              />
            </Box>
          </Box>
        </Grid>
      </Grid>
    </>
  );
}
